version: "2"
services:
  nginx:
    container_name: nginx-server
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - nodeapp
  nodeapp:
    container_name: nodeapp
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db      
  db:
    container_name: dbContainer
    image: mysql:5.7
    volumes:
    - /home/crismon-01/Documenti/TESI/Docker/mysqlLogin/datas:/var/lib/mysql
    ports:
    - 3306
    environment:
     MYSQL_ROOT_PASSWORD: "root"
     MYSQL_USER: "root"
     MYSQL_PASSWORD: ""
     MYSQL_DATABASE: "Geolocation"